### ISSUE TITLE
大佬，请问你的qt版本和编译器是多少的，我这边会报crash.exe

### ISSUE THREAD

**Issue by CasonTsai** [HackersSpirit/tensorflow-qtcreator-cppApi#1]

**Comment by HackersSpirit** [comment]
@caishengzao : Qt version 5.8.0
Compiler: msvc2015

**Comment by CasonTsai** [comment]
@HackersSpirit 
thank you !!!  i found that should put the lib*and dll files into the release file so there is no more crash fault

**Comment by HackersSpirit** [comment]
@caishengzao : ohh yes. Actually i would update this part in the documentation as most of the time we forget to do so as we get used to the debug mode.
